<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8qjuv3c\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8qjuv3c/appProdProjectContainer.php') {
    touch(__DIR__.'/Container8qjuv3c.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container8qjuv3c\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container8qjuv3c\appProdProjectContainer(array(
    'container.build_hash' => '8qjuv3c',
    'container.build_id' => 'd279972a',
    'container.build_time' => 1546937543,
), __DIR__.\DIRECTORY_SEPARATOR.'Container8qjuv3c');
